---
- name: Testing Connectivity
  hosts: all
  become: yes

  tasks:
    - name: Test connectivity to an external site
      uri:
        url: https://www.google.com
        return_content: yes
      register: test_response

    - name: Display test connectivity result
      debug:
        msg: "Connectivity Test Response: {{ test_response.content[:100] }}"
